target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../target/" + target + "/" + mode + "/"
shared-elf := build-path + "shared-scheduler"
shared-bin := build-path + "shared-scheduler.bin"

objdump := "riscv64-linux-gnu-objdump"
objcopy := "rust-objcopy --binary-architecture=riscv64"
gdb := "riscv64-unknown-elf-gdb.exe"
size := "rust-size"

threads := "2"

build: shared-scheduler
    @{{objcopy}} {{shared-elf}} --strip-all -O binary {{shared-bin}}

shared-scheduler:
    @cargo build --target={{target}}

asm: build
    @{{objdump}} -D {{shared-elf}} | less

size: build
    @{{size}} -A -x {{shared-elf}} 
