target := "riscv64imac-unknown-none-elf"
mode := "release"
build-path := "../target/" + target + "/" + mode + "/"

user-elf := build-path + "tornado-user"
user-bin := build-path + "tornado-user.bin"

objcopy := "rust-objcopy --binary-architecture=riscv64"

build: user
    @{{objcopy}} {{user-elf}} --strip-all -O binary {{user-bin}}

user:
    @cargo build --target={{target}} --{{mode}}