target := "riscv64imac-unknown-none-elf"
mode := "release"
build-path := "../target/" + target + "/" + mode + "/"

user-elf := build-path + "tornado-user"
user-bin := build-path + "tornado-user.bin"

objcopy := "rust-objcopy --binary-architecture=riscv64"

build app: (elf app)
    @{{objcopy}} {{user-elf}} --strip-all -O binary {{user-bin}}

elf app:
    @cargo build --target {{target}} --{{mode}} --bin {{app}}
