target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../target/" + target + "/" + mode + "/"

user-elf := build-path + "tornado-user"
user-bin := build-path + "tornado-user.bin"

objcopy := "rust-objcopy --binary-architecture=riscv64"
objdump := "riscv64-unknown-elf-objdump"
size := "rust-size"

build app: elf
    @{{objcopy}} {{build-path}}/{{app}} --strip-all -O binary {{build-path}}/{{app}}.bin

elf:
    @cargo build --target={{target}} --bins

asm app: elf
    @{{objdump}} -D {{build-path}}/{{app}} | less

size app: elf
    @{{size}} -A -x {{build-path}}/{{app}}
    